routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
//    return "Hello world";
    return view('welcome');
});

//Route for add new task

//Route::get('/add_task',function(){
//    return view('add');
//});
//Route::post('/add_task',function(){
//
//   return "about to add";
//});
Route::resource('/add_task','TaskController');

Auth::routes();

Route::get('/out',function(){
    return "Outputtting";
});

Route::get('/out/{na}',function($na){
    if($na=="na")
    {return "oww you too";}
    else
    return "Outputtting name: ".$na;
});

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Task extends Model
{
    //mass assignment
    protected $fillable=[
        'name','status'
    ];

    //Use soft deletes
    Use SoftDeletes;
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\TaskRequest;
use App\Task;
use Illuminate\Http\Request;
use Session;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //Getting all tasks
        $tasks = Task::latest()->orderBy('created_at','desc')->get();
        if($tasks->count()<1) {
            Session::flash('warning', 'No tasks found');
            return view('all', compact('tasks'));
        }
        else{
//            Session::flash('info', $tasks->count().' task(s) found');
            return view('all',compact('tasks'));

        }


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        Session::flash('info',' Add a task');

        return view('add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TaskRequest $request)
    {
        //
//        $store = new Task();
//        $store->name = $request->name;
//        $store->status = $request->status;
//        $store->save();

        Task::create($request->all());
        Session::flash('success',' new task created');

        return redirect(route('add_task.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //grab a particular record
        $task=Task::find($id);
       // dd($task);
        Session::flash('info', ' task ready for update');

        return view('edit',compact('task'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TaskRequest $request, $id)
    {
        //
        Task::find($id)->update($request->all());
        Session::flash('info', ' task updated');

        return redirect(route('add_task.index'));
//        $updatedTask = Task::find($id);
//        dd($updatedTask);
//        $updatedTask->update($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Task::destroy($id);
        Session::flash('danger',' task deleted');

        return redirect(route('add_task.index'));
    }
}

resources/views/add.blade.php
@extends('layouts.parent')

@section('killer')

    <div class="col-md-offset-3">
        <div class="col-md-6">
            {!! Form::open(['route'=>'add_task.store','class'=>'form']) !!}
            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
            {!! Form::label('Name of Task') !!}

            {!! Form::text('name',null,['class'=>'form-control']) !!}
                @if ($errors->has('name'))
                    <span class="help-block">
                        <strong>{{ $errors->first('name') }}</strong>
                    </span>
                @endif
            </div>
            {!! Form::label('Status') !!}

            {!! Form::select('status',['completed'=>'Completed','uncompleted'=>'Un-completed'],'uncompleted',['class'=>'form-control']) !!}
            <br>
            {!! Form::submit('Save',['class'=>'btn btn-primary btn-block']) !!}
            {!! Form::close() !!}

        </div>

    </div>



    @endsection

resources/views/all.blade.php
@extends('layouts.parent')

@section('killer')

    <div class="col-md-offset-3">
        <div class="col-md-9">
           <table class="table table-responsive table-striped">
               <thead>
                <th>Name</th>
                <th>Status</th>
                <th>Time Elapsed</th>
                <th>Last Update</th>
                <th>Edit</th>
                <th>Delete</th>
               </thead>
               <tbody>
            @if(!empty($tasks))
                @foreach($tasks as $task)
                <tr>
                    <td>{{$task->name}}</td>
                    <td>{{$task->status}}</td>
                    <td>{{$task->created_at->diffForHumans()}}</td>
                    <td>{{$task->updated_at->diffForHumans()}}</td>
                    <td><a href="{{route('add_task.edit',$task->id)}}" class="btn btn-primary fa fa-edit"></a></td>
                       {!! Form::open(array("route"=>["add_task.destroy",$task->id],'method'=>'delete')) !!}
                    <td><button  type="submit" class="btn btn-danger" ><span class="fa fa-trash-o fa-2x"></span></button></td>

                    {!! Form::close() !!}


                </tr>
                @endforeach
             @endif
               </tbody>
           </table>

        </div>

    </div>



    @endsection

resources/views/edit.blade.php
@extends('layouts.parent')

@section('killer')

    <div class="col-md-offset-3">
        <div class="col-md-6">
            {!! Form::model($task,['route'=>['add_task.update',$task->id],'method'=>'patch','class'=>'form']) !!}
            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
            {!! Form::label('Name of Task') !!}

            {!! Form::text('name',null,['class'=>'form-control']) !!}
                @if ($errors->has('name'))
                    <span class="help-block">
                        <strong>{{ $errors->first('name') }}</strong>
                    </span>
                @endif
            </div>
            {!! Form::label('Status') !!}

            {!! Form::select('status',['completed'=>'Completed','uncompleted'=>'Un-completed'],$task->status,['class'=>'form-control']) !!}
            <br>
            {!! Form::submit('Update',['class'=>'btn btn-warning btn-block']) !!}
            {!! Form::close() !!}

        </div>

    </div>



    @endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/css/app.css" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Login</a></li>
                            <li><a href="{{ url('/register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="/js/app.js"></script>
</body>
</html>

resources/views/layouts/parent.blade.php
<!Doctype>
<html>
    <head>
        <title>Task App</title>
        <link rel="stylesheet" type="text/css" href="{{URL::asset('css/font-awesome.min.css')}}">
        <link rel="stylesheet" type="text/css" href="{{URL::asset('css/bootstrap.min.css')}}">
    </head>
<body>

    <div class="container">
        <div class="col-md-12">
            <!--Place navigation bar-->
        @include('partials.navbar')
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-3">
                @if(Session::has('success'))
                    <div class="alert alert-success">{{Session::get('success')}}</div>
                @endif
                @if(Session::has('danger'))
                    <div class="alert alert-danger">{{Session::get('danger')}}</div>
                @endif
                @if(Session::has('info'))
                    <div class="alert alert-info">{{Session::get('info')}}</div>
                @endif
                @if(Session::has('warning'))
                    <div class="alert alert-warning">{{Session::get('warning')}}</div>
                @endif
            </div>

            <div class="col-md-12">
                <!--Content Area-->

                @yield('killer')
            </div>
        </div>


    </div>


</body>

<script src="{{URL::asset('js/jquery.min.js')}}"></script>
<script src="{{URL::asset('js/bootstrap.min.js')}}"></script>
<script src="{{URL::asset('js/custom.js')}}"></script>
</html>

resources/views/partials/navbar.blade.php
<nav class="navbar navbar">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><img class="logo" width="70" src="\images\tapplogo.png" alt="TapP Logo"></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{{url('/')}}">Home <span class="sr-only">(current)</span></a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Operations <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{route('add_task.create')}}">Add New Task</a></li>
                        <li><a href="{{route('add_task.index')}}">Edit/Delete Task</a></li>
                        <li><a href="{{route('add_task.index')}}">All Task</a></li>

                    </ul>
                </li>
            </ul>


        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>